dist: trusty
sudo: false

language: php
php:
  - '5.6'
  - '7.0'

install:
  - composer install

script:
  - vendor/bin/phpcs -n -p --encoding=utf-8 --standard=PSR2 --extensions=php airbrake-wordpress.php
